# Homebrew Cask for Meeting Assistant (macOS).
# GENERATED by packaging/macos/render-release-cask.sh — do not edit by hand.
#
# Free (un-notarized) channel: the app is ad-hoc signed and NOT notarized (no
# paid Apple Developer ID — see packaging/macos/HOMEBREW-SUNSET.md). The
# postflight strips com.apple.quarantine so Gatekeeper does not wall off the app
# on a clean machine. Lives in a SELF-HOSTED tap (homebrew/cask will not accept
# an un-notarized cask). Install (Homebrew 6+ asks you to `brew trust` it once,
# because the postflight runs a command to strip the quarantine flag):
#
#   brew tap medvedevd/meeting-assistant
#   brew install --cask meeting-assistant
cask "meeting-assistant" do
  version "0.1.0-alpha.8"
  sha256 "0b4c9a4a65c6e6337abf68b230aa401ca56e187c4fbfaff5e47cd30880611fde"

  url "https://github.com/medvedevD/meeting-assistant/releases/download/v0.1.0-alpha.8/MeetingAssistant-0.1.0.dmg",
      verified: "github.com/medvedevD/meeting-assistant/"
  name "Meeting Assistant"
  desc "Record, transcribe, and generate meeting protocols"
  homepage "https://github.com/medvedevD/meeting-assistant"

  auto_updates false
  depends_on macos: :ventura # macOS 13 floor (ScreenCaptureKit)

  app "MeetingAssistant.app"

  # Un-notarized: drop the quarantine xattr so the app launches on a clean Mac
  # without the Gatekeeper "cannot verify" wall. This is the entire reason the
  # cask exists for the free channel (see packaging/macos/HOMEBREW-SUNSET.md).
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/MeetingAssistant.app"]
  end

  uninstall quit: "com.meeting-assistant.app"

  # Clean uninstall: mirror the Rust core's XDG-style layout on macOS
  # (rust/crates/app/src/container.rs + adapters/src/settings_store.rs).
  zap trash: [
    "~/.cache/meeting-assistant",
    "~/.config/meeting-assistant",
    "~/.local/share/meeting-assistant",
  ]
end
